data <- read.csv("C:\\Users\\user\\Desktop\\R\\iris.csv")
summary(data)
model <- lm(data$sepal_length ~ data$species + data$sepal_width + data$petal_length + data$petal_width)
plot(data)
summary(model)
resid(model)
fitted(model)
par(mfrow=c(2,2))
plot(model)
